### ISSUE TITLE
Zero (0) retorna `undefined` em `{mode: 'number'}`

### ISSUE THREAD

**Issue by neuberoliveira** [lusofonia/extenso.js#58]
`extenso('0', {mode: 'number'})` retorna `undefined` ao invés de `zero`

Se o mode for `currency` funciona OK, mas numerico não

usando a versao `2.0.1`

**Comment by theuves** [comment]
O pior é que não consegui simular esse problema. Sabe dizer em qual plataforma isso acontece?

**Comment by theuves** [comment]
Consegui realizar um teste e simular o erro.

Parece ocorrer pelo Node.js.

Testei com o Node.js v21.7.1.

**Comment by theuves** [comment]
Ocorre com:

```
extenso('0', {mode: 'number'})
extenso('0')
extenso(0)
```

**Comment by theuves** [comment]
Problema provavelmente está relacionado ao build do Webpack e não ao código-fonte. Todos os testes estão passando.

**Comment by theuves** [comment]
Na verdade foi corrigido em 67b000f.

Vamos publicar a correção.

**Comment by theuves** [comment]
Era um problema de #33, #34. Não lembrava. Perdão.
