### ISSUE TITLE
Problema de importação no React Native

### ISSUE THREAD

**Issue by GGarnize** [lusofonia/extenso.js#61]
Estou com um projeto em react-native, e ao usar "import extenso from 'extenso';
tenho um erro.
`ReferenceError: Property 'module' doesn't exist, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes`

só apagar o uso dele, e nao tem erro, então queria saber se tem alguma maneira de usar ele. 
Eu uso React-Native em um projeto Expo.

**Comment by theuves** [comment]
Olá, Guilherme.

Obrigado pelo registro.

Estamos atualizando a biblioteca para corrigir esses erros. Aviso você aqui assim que lançar a nova versão.

**Comment by theuves** [comment]
Foi lançado na versão 2.1.0 que deve ter corrigido esse problema -> https://github.com/lusofonia/extenso.js/releases/tag/2.1.0
